---
- name: ensure keepalived configuration directory
  file:
    path: "{{ keepalived_conf_dir }}"
    state: "directory"
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: 0644
  become: true

- name: ensure systemd directory
  file:
    path: "{{ keepalived_systemd_dir }}"
    state: "directory"
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: 0644
  become: true
