---
- name: ensure keepalived package
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ keepalived_package_name }}"
        state: "{{ keepalived_package_state }}"
  when: not keepalived_package_version

- name: ensure keepalived package with version
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ keepalived_package_name }}-{{ keepalived_package_version }}"
        state: "{{ keepalived_package_state }}"
  when: keepalived_package_version | length
